LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE        := dashd
LOCAL_MODULE_CLASS  := EXECUTABLES
LOCAL_MODULE_TAGS   := optional
LOCAL_SRC_FILES     := proprietary/sbin/dashd
LOCAL_MODULE_PATH   := $(TARGET_ROOT_OUT_SBIN)
LOCAL_FORCE_STATIC_EXECUTABLE := true
LOCAL_UNSTRIPPED_PATH := $(TARGET_ROOT_OUT_SBIN_UNSTRIPPED)
include $(BUILD_PREBUILT)
